# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Average Developer
author: Willian Carvalho
description: Powered by HI (Human Intelligence)
email: willianc@pm.me
# description: >- # this means to ignore newlines until "baseurl:"
#   Blog and stuff
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "/"
url: "https://willianpc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  willianpc


# Build settings
theme: minima

 social_links:
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/wcarvalho" }

